version: "3.9"

services:
  basics:
    image: basics_image:dev
    build:
      context: ./Basics
      dockerfile: Dockerfile
    container_name: basics_container
    volumes:
      - ./Basics:/app # Bind mount host folder to container
    tty: true
